### PR TITLE
Server init function and config extractor

### PR DESCRIPTION
**Pull request by mpgermano**
Pulled server initialization into separate function
Added a config extractor function

### CODE REVIEW

**Comment by gilb195** [comment]
You should also check for an upper bound on the port number. Also, don't hardcode the extraction in the future.

**Comment by mpgermano** [comment]
Sounds good. I'll fix that in the next commit.

**Comment by mpgermano** [comment]
@gilb195 check the new commit and let me know if you think that looks good.

**Review by AustinNassoUCLA — APPROVED** [review]
I think this looks great - really helps with code readability. Now our code can handle different config files!

**Pull request merged**
